

   parameter songLength = 25;
   parameter [0:(15*songLength)-1] noteList = {_G,
					       _G,
					       _A,
					       _B,
					       _G,
					       _B,
					       _D>>1,
					       _G>>1,
					       _G>>1,
					       _Fs>>1,
					       _G>>1,
					       _D>>1,
					       _B,
					       _G,
					       _C>>1,
					       _E>>1,
					       _C>>1,
					       _B,
					       _D>>1,
					       _B,
					       _G,
					       _A,
					       _D>>1,
					       _D>>1,
					       _D>>1};


   parameter [0:(5*songLength)-1] durationList = {5'd4,
						  5'd3,
						  5'd1,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd4,
						  5'd3,
						  5'd1,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd4,
						  5'd3,
						  5'd1,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd2,
						  5'd4,
						  5'd3,
						  5'd1,
						  5'd8};
